version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.5-node-browsers
    steps:
      - checkout
      - run: pip install numpy --user
      - save_cache:
          key: pip_cache
          paths:
            - my_cache
