version: 2
jobs:
  one:
    docker:
      - image: circleci/python:3.5-node-browsers
    steps:
      - checkout
      - run: echo "A first hello"
      - run: mkdir -p my_workspace
      - run: echo "testing out workspaces" > my_workspace/hello
      - persist_to_workspace:
           root: my_workspace
           paths:
               - hello
  two:
    docker:
      - image: circleci/python:3.5-node-browsers
    steps:
      - checkout
      - run: echo "A second hello"
      - attach_workspace:
          at: my_workspace
      - run: |
          if [[ $(cat my_workspace/hello) == "testing out workspaces" ]]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1;
          fi

workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two:
          requires:
            - one
