version: 2
jobs:
  one:
    docker:
      - image: circleci/python:3.5-node-browsers
    steps:
      - checkout
      - run: echo "A first hello"
  two:
    docker:
      - image: circleci/python:3.5-node-browsers
    steps:
      - checkout
      - run: echo "A second hello"
