version: 2
jobs:
  one:
    docker:
      - image: circleci/python:3.5-node-browsers
    steps:
      - checkout
      - run: echo "A first hello"
  two:
    docker:
      - image: circleci/python:3.5-node-browsers
    steps:
      - checkout
      - run: echo "A second hello"

workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two
